### ISSUE TITLE
fail to download ASTER LST data

### ISSUE THREAD

**Issue by ChangpeiHe** [DHI-GRAS/earthdata_download#23]
ValueError: No HTTPS or FTP data URL found among URLs ['https://e4ftl01.cr.usgs.gov//WORKING/BRWS/Browse.001/2020.01.02/pg-BR1A0000-2020010201_003_001.1.VNIR.jpg', 'https://e4ftl01.cr.usgs.gov//WORKING/BRWS/Browse.001/2020.01.02/pg-BR1A0000-2020010201_003_001.2.SWIR.jpg', 'https://e4ftl01.cr.usgs.gov//WORKING/BRWS/Browse.001/2020.01.02/pg-BR1A0000-2020010201_003_001.3.TIR.jpg', 'https://lpdaac.usgs.gov', 'https://asterweb.jpl.nasa.gov/', 'https://doi.org/10.5067/ASTER/AST_08.003', 'https://search.earthdata.nasa.gov/search?q=C1299783630-LPDAAC_ECS', 'https://lpdaac.usgs.gov/documents/69/AST_L1_User_Guide_V3.pdf', 'https://lpdaac.usgs.gov/documents/64/AST_08_User_Guide_V3.pdf', 'https://lpdaac.usgs.gov/documents/175/ASTER_L1_Product_Specifications.pdf', 'https://lpdaac.usgs.gov/documents/65/AST_08_ATBD.pdf', ' https://lpdaac.usgs.gov/documents/996/ASTER_Earthdata_Search_Order_Instructions.pdf', 'https://lpdaac.usgs.gov/documents/1319/ASTER_User_Handbook_v4.pdf']

**Comment by j08lue** [comment]
What you are seeing is expected behavior: The download routine has some heuristics to find the right URL within the download links - it looks for URLs with a specific scheme and file extension:

https://github.com/DHI-GRAS/earthdata-download/blob/82207f1f52a0f4d5c2642784b8ed2e14db44f709/earthdata_download/download.py#L21-L22

None of the URLs in your example fit the predefined patterns. Would you want to download the JPG files?

If you use `EarthdataAPI` for your workflow, you could specify JPG as a valid file extension when you call 

```python

myapi = EarthdataAPI(...)
entries = myapi.query(...)

for entry in entries:
    url = myapi.get_data_url(entry, ..., extensions=[".jpg"])`
    myapi.download_single(url)
```

If you provide a minimal working example that produces the error, I can help you solve it.

**Comment by ChangpeiHe** [comment]
![image](https://github.com/DHI-GRAS/earthdata-download/assets/126058879/a5927eae-adf2-4c8e-87ce-9272350c04fa)
it is '.hdf'

**Comment by j08lue** [comment]
There are no HDF links for that entry, as you can see from the list of URLs you posted. Maybe it is just one faulty entry - are you able to download other products from that collection?

Minimal Working/Reproducible Example: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by ChangpeiHe** [comment]
thanks，I can download other products.
